### ISSUE TITLE
DatePicker has 100% width

### ISSUE THREAD

**Issue by Saegrov** [fremtind/jokul#796]
**Describe the bug**
The datepicker has 100% width if text-input css is imported after datepicker.css.
`.jkl-datepicker__input` and `.jkl-text-field` has the same specificity and they both set a width.
If text-input is imported last `.jkl-text-field` wins and width is set to 100%.

**To Reproduce**

1. import datepicker css
2. import text-input css (after datepicker)
3. Use datepicker

**Expected behavior**
Datepicker has 12ch + 2rem width

**Screenshots**
![Screenshot 2020-02-28 at 16 05 44](https://user-images.githubusercontent.com/124469/75560564-b25e7700-5a45-11ea-86d0-86f6ef061960.png)

**Comment by SercanSercan** [comment]
Hi @Saegrov, 

Thank you for your detailed task description. I decided to remove text-input CSS from date-picker component. So, the main issue has been fixed. Plus, few other issues along the way were also fixed. For instance, placeholder and calendar icon were very close to each other because of some CSS bug. And date-picker-react component lacked "yarn build:watch". This is added now for dev-environment convenience.

Changes have been merged into master today.

**Comment by Saegrov** [comment]
@SercanSercan This bug still exist:
https://github.com/fremtind/jokul/blob/b5170e1e9ad7e0f3d9cab4088d7d37cb9ae3b23f/packages/datepicker/datepicker.scss#L33

**Comment by SercanSercan** [comment]
Hi @Saegrov ,
But this attribute (on line 33) only applies to .jkl-datepicker. Its child element (.jkl-datepicker-text-input) uses 
`width: calc(12ch + #{$component-spacing--medium} + #{$icon-size});`

Do you still see the bug in your component?

**Comment by Saegrov** [comment]
Yes. If you want to have 2 datepickers side-by-side it won't work since each datepicker has 100% width:
https://codesandbox.io/s/busy-sky-kq29s?fontsize=14&hidenavigation=1&theme=dark

**Comment by SercanSercan** [comment]
datepicker uses "display: block" like other components. The consumer of the datepicker component should wrap them as flex-boxes. I edited your code on sandbox. Please let me know if I have any misunderstandings:

https://codesandbox.io/s/pensive-archimedes-x1iyn

**Comment by Saegrov** [comment]
Imo this is a bad option that cause more work for consumers. 

Since `jkl-datepicker` has `display: block` there is no reason for setting  `width:100%` since it is implicit by using `display: block`. The only effect of setting `width: 100%` is that you have to wrap `DatePicker` if you use it as a flex element. 

I can create a workaround as you suggest, but I see no reason to have to create this workaround since it can be fixed in the component.
